### ISSUE TITLE
Snippy error after conda packages updating

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#101]
Tras actualizar Wombat y todos sus paquetes, ("sí" a la segunda pregunta):

`Remove all packages in environment (/home/instalador/anaconda3/envs/wombat:) Proceed ([y]/n)? y`

aparece un nuevo error en Snippy, que he puesto en su repositorio https://github.com/tseemann/snippy/issues/399#issue-633377726. Hasta ahora funcionaba perfectamente, no sé si el error aparecerá siempre que se instale Wombat de ahora en adelante.

**Comment by ireneortega** [comment]
Al desinstalar y volver a instalar el paquete de snippy en conda, se ha resuelto el problema https://github.com/tseemann/snippy/issues/399#issuecomment-640287812. Se ha descargado la versión de Snippy 4.4.3 (no la 4.6.0) y funciona con la versión SnpEff 4.5covid19 (build 2020-04-15 22:26), by Pablo Cingolani.

Creo que deberíamos cambiar la versión de snippy de Wombat para evitar ese problema al actualizar.

**Comment by JoseBarbero** [comment]
¿Tenías instalada antes la 4.6.0? Según nuestro entorno conda deberías tener la 4.3.6. ¿Es posible que la hayas instalado para otra cosa?
¿A qué pregunta de actualizar paquetes de conda te refieres? ¿Aparece durante la actualización de wombat o al tocar paquetes en conda fuera de la instalación? El usuario no debería actualizar paquetes de conda dentro de ese entorno, si quiere hacerlo debería salir fuera del nuestro.

**Comment by ireneortega** [comment]
No, tenía la 4.3.6, pero al actualizar los paquetes de conda también (sí a la segunda pregunta de abajo), se cambió la versión de snpEff a la 4.5covid19, que era incompatible con la configuración de snippy. Lo que hay que controlar es que snippy vaya con la versión snpEff 4.3 (creo).

Cuando se actualiza Wombat aparecen dos preguntas:
1. La primera la has configurado tú, está asociada a Wombat.
2. La segunda es esta: **Remove all packages in environment /home/instalador/anaconda3/envs/wombat:) Proceed ([y]/n)?** Suelo responder que no, pero el otro día no se ejecutó bien Wombat (era porque había quitado la conexión a Internet) y entonces volví a actualizar Wombat respondiendo que sí a esta pregunta, por si de casualidad se solucionaba. Teniendo en cuenta lo que has dicho, deberíamos poner una advertencia para evitar que al usuario le ocurra lo que me ha pasado a mí.

**Comment by JoseBarbero** [comment]
Pero esa pregunta no te dice si quieres actualizarlos, te dice si quieres borrarlos.
Es lo que confirma que queremos borrar todos los paquetes dentro de nuestro entorno. La respuesta debería ser sí, porque luego conda va a coger las versiones de nuestro fichero. 
No sé qué ha podido haber pasado.
