### ISSUE TITLE
Update PROKKA version 1.14.6

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#104]
En wombat_report https://github.com/JoseBarbero/Wombat/issues/96#issue-612720267, la columna 17 CRISPRs sale vacía porque el archivo Sample.txt (cuando se ejecuta PROKKA) del cual obtiene la información no contiene un campo llamado `CRISPR:` Esto es debido a la versión de PROKKA 1.14. ¿Es posible actualizar a la versión 1.14.6, en la que sí aparece ese campo? (si no es posible actualizar de momento, deja el issue abierto)

**Comment by JoseBarbero** [comment]
Acabo de actualizar a la 1.14.6 y, al menos con mis cepas, no sale nada en CRISPRs. Subo de todas formas la versión nueva por si quieres probarlo con tus cepas.

**Comment by ireneortega** [comment]
No entiendo lo que sucede. Tengo instalado fuera de Wombat la misma versión de PROKKA 1.14.6 y en el archivo Sample.txt aparece `CRISPR:`, pero en la misma versión en Wombat, `CRISPR:` aparece bajo la denominación `repeat_region:`. Así que, en vez de llamar al campo CRISPR en ese archivo, llama al campo repeat_region, pero no cambies el heading del wombat_report (se deberá mantener CRISPRs). De todas formas, los números exactos de CDS, rRNA varían ligeramente según dónde ejecute PROKKA (dentro o fuera de WOMBAT) y no entiendo por qué (con el mismo comando).

**Comment by JoseBarbero** [comment]
Lo único que se me ocurre es que a conda hayan subido una versión distinta a la que tienen fuera con el mismo nombre 1.14.6.
De momento lo saco con repeat_region y si suben alguna versión nueva a conda actualizamos.

**Comment by ireneortega** [comment]
No veo que se rellene la columna CRISPRs del wombat_report con el campo repeat_region: del archivo Sample.txt anotado por PROKKA.
