### ISSUE TITLE
Draft_genomes and Mauve_reordered_draft_genomes dir

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#107]
Cuando se ejecuta MAUVE, la carpeta que permanece es Draft_genomes en vez de Mauve_reordered_draft_genomes https://github.com/JoseBarbero/Wombat/issues/4#issuecomment-643655124. No he hecho la prueba sin indicar el archivo fasta de referencia para ordenar y evitar la ejecución de MAUVE, para comprobar qué carpeta pemanece.

Si se ejecuta MAUVE, debe permanecer solo la carpeta Mauve_reordered_draft_genomes. Si no se ejecuta, 
debe permanecer solo la carpeta Draft_genomes.

**Comment by ireneortega** [comment]
Sigue sin salir la carpeta adecuada cuando se ejecuta MAUVE.

**Comment by JoseBarbero** [comment]
Acabo de probar y a mí sí me sale la carpeta Mauve_reordered_draft_genomes cuando ejecuto Mauve.
Lo mismo que para el otro commit: intenta actualizar y si te sigue pasando me pasas el fichero de configuración y el report.

**Comment by ireneortega** [comment]
Solucionado (no había actualizado)
