### ISSUE TITLE
wombat_report

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#108]
- [ ] 1. Algo pasa con la tabla de wombat_report en las columnas asociadas a los resultados de los genes de virulencia obtenidos con BLAST. Tiene la siguiente forma:

adhesion(28) | capsule(8) | chemotaxis(20) | colonization(0) | invasion(22) | iron(12) | los(6) | motility(40) | n-linked_glycosylation(4) | stress(64) | t6ss(2) | toxin(12) | Total (218) | adhesion(0) | capsule(0) | chemotaxis(0) | invasion(0) | iron(0) | los(0) | motility(0) | n-linked_glycosylation(0) | stress(0) | t6ss(0) | toxin(0)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   | 0 |   |   |   |   |   |   |   |   | 52 | 6 | 2 | 5 | 5 | 3 | 1 | 9 | 1 | 16 | 1 | 3
  |   |   | 0 |   |   |   |   |   |   |   |   | 52 | 6 | 2 | 5 | 5 | 3 | 1 | 9 | 1 | 16 | 1 | 3
  |   |   | 0 |   |   |   |   |   |   |   |   | 57 | 8 | 2 | 5 | 6 | 3 | 2 | 11 | 1 | 16 | 0 | 3
  |   |   | 0 |   |   |   |   |   |   |   |   | 57 | 8 | 2 | 5 | 6 | 3 | 2 | 11 | 1 | 16 | 0 | 3

Por otra parte, el encabezado de esas columnas debe depender solo del contenido del archivo custom_VFDB.txt (mientras este archivo no se modifique, el encabezado de esas columnas es fijo) y no del número de samples que se utilizan. Es decir, el número entre paréntesis de cada columna no es la suma de las filas hacia abajo que tenemos ahora, sino el número de veces que la palabra del encabezado ">" aparece en segunda posición en el archivo custom_VFDB.txt, después del nombre del gen. Por ejemplo, si ese archivo custom_VFDB.txt tuviera esta forma:
```
>ppk1 Stress
xxxxxxxxx
>ppk2 Stress
xxxxxxxxx
>abcd Adhesion
xxxxxxxxx
```

Stress aparece 2 veces y Adhesion 1. Entonces, en el wombat report, debe aparecer:

adhesion(1) | stress(2) | Total (3)

de forma que Total = 1 +2, es la suma de los números entre paréntesis de esas columnas.

- [ ] 2. Tampoco veo veo que se rellene la columna CRISPRs del wombat_report con el campo repeat_region: del archivo Sample.txt anotado por PROKKA https://github.com/JoseBarbero/Wombat/issues/104#issuecomment-648358436

**Comment by JoseBarbero** [comment]
Estos fallos deberían estar solucionados por los commits:

1. https://github.com/JoseBarbero/Wombat/commit/d2aec0ef9a8add6c66bded8540b0c201b7c63cce
2. https://github.com/JoseBarbero/Wombat/commit/1bfe726e9cff2d78a5a63f654e698be98b432ce0

Acabo de probar y a mí me salen bien. ¿Estás en la última versión? Intenta actualizar ahora que acabo de subir un pequeño cambio nuevo. ¿Si estás ya en la última versión y te sigue dando el fallo me puedes pasar tu fichero de configuración para intentar replicarlo?

**Comment by ireneortega** [comment]
Respecto al commit:
1. Aparece LOS(6) cuando debe ser LOS(5) porque de esa categoría hay 5 secuencias, aunque aparezcan 6 cadenas de texto "los" en todo el documento. Creo que debes acotar esa búsqueda entre el primer y segundo espacio de cada encabezado que empieza por ">".

En el código escribe un comentario de que la proteína capA de esa db está separada en 2 secuencias y que se cuenta como si fueran dos diferentes, porque en wombat_report se cuenta 2 veces cuando debería contarse 1. Lo podrías considerar para ese recuento del report, pero no hagas nada porque igual se termina quitando esa proteína de la db porque hay algunas proteínas que no estoy segura de si tBLASTn es adecuado.

De todas formas, la tabla tiene esta forma (y sigue):

Total (218) | Total (15) | adhesion(10) | capsule(2)
-- | -- | -- | --
  | 52 | 6 | 2
  | 52 | 6 | 2
  | 57 | 8 | 2
  | 57 | 8 | 2

y se generan dos columnas de Total, ninguna de ellas es la suma de los números entre paréntesis de cada categoría.

2. Solucionado (no había actualizado)

**Comment by JoseBarbero** [comment]
Tienes razón, no había tenido en cuenta que la cadena podría aparecer más veces. Voy a tener en cuenta ahora solo lo que está entre el primer y el segundo espacio, como dices, pero me surgen algunas dudas. Eso funcionaría en el caso de que la categoría sea en el 100% de los casos una sola palabra, si fueran varías fallaría. ¿Es posible que en un futuro en esas categorías haya varias palabras? Por saber cómo enfocarlo mejor.

El tema de las columnas "Total" está solucionado ya.

**Comment by ireneortega** [comment]
A tu pregunta, sí, es posible que una categoría este definida por más de una palabra. Concretamente tenemos una llamada N-linked_glycosylation, pero sabiendo que eso podría suceder, incluí el guión bajo para evitar ese posible problema. Hasta donde yo puedo imaginar, esa consideración me parece la más fácil. Solo habría que tenerlo en cuenta para otra casos
