### ISSUE TITLE
Sharing Conda Environments Across Different Operating Systems

### ISSUE THREAD

**Issue by OtakuZerg** [JoseBarbero/Wombat#143]
Dear José,

Thank you for your excellent work and for sharing your contributions. I am very interested in this topic and appreciate the insights you’ve provided.

However, I’ve encountered some difficulties installing packages using the provided campype_env.yml file, likely due to differences in my operating system (MacOS).

Would it be possible for you to share a version of the campype_env.yml and campype_env_aux.yml file with the "no-builds" option enabled? 

Thank you for your time and support!

Sincerely,
George Chen

**Comment by JoseBarbero** [comment]
Hi George,

I've attached the .yml files. Hopefully you can get it to work on MacOS.

Regards,

[no_builds_envs.zip](https://github.com/user-attachments/files/18019792/no_builds_envs.zip)

**Comment by OtakuZerg** [comment]
Dear José,

Thank you very much for your help.

Best regards,
George
