### ISSUE TITLE
Include Mauve.

### ISSUE THREAD

**Issue by JoseBarbero** [JoseBarbero/Wombat#33]
También hay que incluir MAUVE para ordenar los contigs en base a un genoma de referencia. Esto lo tengo que mirar bien porque de incluirlo, lo suyo sería que luego se anote el genoma sobre los contigs ordenados y he visto que DFAST no respeta el nombre de los contigs ordenados, sino que los renombra secuencialmente. Por ejemplo, si tras ordenar los contigs, el que se llama C_39 se sitúa en quinta posición, DFAST lo identifica como sequence_05. Lo ideal sería poder cambiar sequence_05 por C_39 en todos los outputs de DFAST, ¿sería
 esto posible? Otra solución sería procesar el archivo Excel con las anotaciones generado por DFAST, de forma que cada contig renombrado se identifique también con el nombre que tenía en el input de DFAST (el genoma con los contigs ordenados), es decir, sequence_05=C_39.

Pero esto no cambiaría todos los outputs de DFAST como me interesa.

**Comment by ireneortega** [comment]
(después de cambiar los nombres de las carpetas como se indica en https://github.com/JoseBarbero/Wombat/issues/4#issuecomment-643655124)

En el archivo de configuración, si el usuario no rellena el campo `"file":` con el archivo del genoma de referencia, se debe omitir la ejecución de Mauve. Cuando esto suceda, todas las siguientes herramientas siguientes utilizarán como input los fasta de la carpeta _Draft_genomes_. 

Es decir, si se ejecuta Mauve, los inputs siguientes serán los de la carpeta _Mauve_reordered_draft_genomes_. Si no se ejecuta Mauve, los inputs serán los de la carpeta _Draft_genomes_.
