### ISSUE TITLE
Set contig length = 500

### ISSUE THREAD

**Issue by JoseBarbero** [JoseBarbero/Wombat#48]
Respecto a la longitud para eliminar contigs, creo que hemos tenido un malentendido porque ese valor debe ser único para todas las cepas. Perdón porque no te lo aclaré lo suficiente. Creo que la mejor opción ahora mismo es que lo configures manualmente con 500 pb, que es el valor adecuado según nuestro tipo de secuenciación. Para que no te suponga mucho lío, déjalo apartado de forma similar a Trimmomatic, y ya volveremos sobre ello porque lo que más interesa es configurar el workflow para adaptarlo a nuestras cepas. Cuando tengamos nuestros resultados, ya volveremos a optimizar esa parte. Además, también será necesario indicar en algún sitio cuál es ese valor. Una opción podría ser indicarlo en el nombre de la carpeta (ejemplo, Contigs_renamed_shorten<500) o que se genere un archivo dentro de esa carpeta donde se indique esa información.

**Comment by ireneortega** [comment]
Para confirmar, esta opción debe ser:
`min_contig_len => 500` (deben permanecer los contigs con una longitud **igual o superior** al valor).
