### ISSUE TITLE
Prokka parameters

### ISSUE THREAD

**Issue by JoseBarbero** [JoseBarbero/Wombat#74]
Vamos a incorporar 3 opciones más para PROKKA, que deberán aparecer en el archivo de workflow_config.py para que el usuario las pueda activar o no, es decir, serán opcionales:
--proteins reference_files/NCTC11168_NCBI.gb #Esta opción permite empezar a anotar cada genoma utilizando ese archivo (te lo envío). Ese archivo
 es la anotación de la cepa de referencia que hay en NCBI, por lo que, de esta forma reducimos el “problema” de tener genes nombrados de forma diferente y utilizamos la codificación de NCBI. Ese archivo se descarga de NCBI de la siguiente forma. En
https://www.ncbi.nlm.nih.gov/nuccore/AL111168 hay una opción arriba a la derecha llamada “Send to” con un triángulo pequeño hacia abajo (a la izquierda del recuadro “Change Region Shown”. Ahí
 tienes que clicar en Complete Record > Choose Destination: File > Format: 
GenBank (full). Espero que no de problemas la ejecución de PROKKA con ese archivo que te adjunto (a mí no me dio) porque lo edité y no lo descargué con la opción que te digo, porque lo supe después. Como te indico en la opción, este archivo deberá incluirse
 en la carpeta reference_files.
--metagenome #Para anotar genomas fragmentados, como es nuestro caso. Esta opción solo se añadirá en las muestras, en la cepa de referencia
 no porque el genoma está completo.
--rawproduct #Para mantener la misma anotación que el archivo NCTC11168_NCBI.gb porque si no cambia muchos nombres a “hypothetical protein”
 y así todo queda igual que en NCBI cuando lo anote. Este comando se debe incluir en las cepas de referencia y en las muestras.
 
Es decir, el comando de PROKKA debe quedar así para las muestras:
prokka Sample.fasta --outdir PROKKA_annotation/Sample --proteins NCTC11168_NCBI.gb --prefix Sample --locustag Sample_L --genus Campylobacter --species jejuni --strain Sample --kingdom Bacteria --gcode
 11 --metagenome –rawproduct
 
y para la cepa de referencia NCTC11168, sin la opción --metagenome
prokka reference_files/NCTC11168.fasta --outdir PROKKA_annotation/NCTC11168--proteins NCTC11168_NCBI.gb --prefix NCTC11168 --locustag NCTC11168_L --genus Campylobacter --species jejuni --strain NCTC11168
 --kingdom Bacteria --gcode 11–rawproduct

**Comment by ireneortega** [comment]
En PROKKA, la opción `--proteins`, tanto para la anotación de las muestras como de la cepa de referencia, debe ser opcional. Se puede poner en el archivo wombat_config.py una opción como, por ejemplo:
`reference_annotation: True #Use reference genome annotation GenBank file to first annotate from (Default: True)`

**Comment by ireneortega** [comment]
Del archivo de configuración, se deben quitar estas dos opciones, que deberán estar así implantadas por defecto en el código:
`"kingdom": "Bacteria"`
`"gcode": 11`

(El desarrollo de Wombat estará centrado en bacterias únicamente)
