### ISSUE TITLE
SPAdes new parameters

### ISSUE THREAD

**Issue by JoseBarbero** [JoseBarbero/Wombat#75]
El problema de SPAdes de que no se ejecuta por problema de memoria no lo consigo quitar porque, aunque lo limita automáticamente por debajo de la RAM de la máquina virtual, se detiene la ejecución.
 Pero he probado que si incorporo la opción -m (número) en el comando de SPAdes, me funciona perfectamente dentro de Wombat. Así que, añádelo también en el archivo worklow_config.py. Por defecto, configúralo como una opción “vacía”, porque así para otros
 usuarios es como si no se usara esa opción, pero para mí escribo ahí un número por debajo de la RAM de la máquina virtual y listo. Además, si en el futuro le pasa a alguien también, ya lo tendríamos resuelto.
Por otra parte, como ya conocemos la longitud de las lecturas que usa SPAdes, para reducir el tiempo de ejecución cuando lo vuelva a correr con todas las cepas de nuevo, incorpora también esta opción
-k (número). Al igual que antes, para que a otros usuarios SPAdes calcule los valores de forma automática, deja ese campo vacío en el archivo worklow_config.py y ya pongo yo 127 y disminuyo el tiempo de ejecución.

**Comment by ireneortega** [comment]
De momento solo añade la opción -k. La opción -m, no, porque he conseguido solucionar el problema de RAM
