### ISSUE TITLE
SNIPPY and roary_plots error

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#79]
En SNIPPY, la referencia al archivo anotado NCTC11168.gbk (con PROKKA o DFAST) debe estar mal porque aparece este error: **Invalid --reference filename**. Antes no ocurría esto.

roary_plots no genera los 3 gráficos, solo uno y aparece este error: **FileNotFoundError: File b'home/MLST/MLST_edited.txt' does not exist**

**Comment by JoseBarbero** [comment]
El error de SNIPPY está solucionado, pero el de roary_plots a mí no me ocurre. ¿Puedes mandarme el log de esa ejecución?


PD: Mejor crear un issue diferente para cada bug

**Comment by ireneortega** [comment]
[wombat_log.txt](https://github.com/JoseBarbero/Wombat/files/4532881/wombat_log.txt)

Creo que el fallo está en la ruta donde se localiza el archivo MLST_edited.txt porque lo he cambiado manualmente en roary_plots.py y funciona bien.

**Comment by ireneortega** [comment]
Aunque algo raro sucede 
![pangenome_matrix](https://user-images.githubusercontent.com/58036036/80279865-686dd680-8700-11ea-9bc2-e3ee77c919ff.png) Si te fijas, las cepas que empiezan por H2xx, los números xx se ponen después de { }, osea se corta el nombre de la Sample. He utilizado este archivo 
[roary_plots.txt](https://github.com/JoseBarbero/Wombat/files/4532934/roary_plots.txt) con este MLST_edited.txt 
[MLST_edited.txt](https://github.com/JoseBarbero/Wombat/files/4532924/MLST_edited.txt)
 En este archivo he puesto "." en los ST vacíos porque si no daba error. Igual esos campos vacíos los has configurado de alguna forma, pero te informo de que ese archivo MLST_edited.txt no ha salido de una ejecución de Wombat, lo he copiado de varias veces. Iugal por eso sale mal lo del H2xx

**Comment by JoseBarbero** [comment]
Ya debería estar solucionado lo de la ruta y lo del árbol.
Cierro el issue, si te da problemas de nuevo, puedes volver a abrirlo.
