### ISSUE TITLE
Antimicrobial resistance genes with ABRicate and new tool AMRFinder

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#89]
Para identificar genes de resistencia antimicrobianos (AMR genes) tenemos ahora la db ResFinder a través de ABRicate, una db que se debe actualizar. Entonces, vamos a crear dos posibilidades para identificar este tipo de genes, basadas en diferentes BLAST (ABRicate con blastn –alineamiento en nucleótidos– y AMRFinderPlus con blastx –alineamiento en proteínas–), de una forma similar a la ejecución para Virulence_genes. Para ello, es necesario crear una nueva carpeta llamada Antimicrobial_resistance_genes, dentro de Wombat_OUTPUT_XXXX. El banner del Step 13 pasará a llamarse _Step 13: Antimicrobial resistance genes_. No sé si es mejor que la ejecución de cada programa tenga su propio banner. En ese caso yo pondría otro banner debajo de Step 13 con el nombre del programa: ABRicate o AMRFinder. Lo puedes hacer como quieras.

Si el usuario no quiere ejecutar alguna de esas herramientas (ABRicate o AMRFinderPlus o ambas), se configurará la opción como `False` (explicado más adelante). Estaría bien que en el archivo de configuración, se indique que las opciones configurables sean para `antimicrobial resistance genes`. De una forma similar al apartado `annotator`.

### OPCIÓN 1. ABRicate
Mantenemos ABRicate pero cambiando la base de datos por defecto a _card_, que será la que aparezca en la línea llamada ahora `bacteria_database` del wombat_confip.py (sustituir resfinder por card). Hay que añadir este comentario: _# Select database from ABRicate to identify antimicrobial resistance genes: argannot, card, ecoh, ecoli_vf, megares, ncbi or resfinder. Remember, ABRicate uses blastn._ 
**Me gustaría actualizar la versión de ABRicate de conda para que se actualicen esas bases de datos y se incluya una nueva columna RESISTANCE en la matriz 1/0**. Aunque se pueden actualizar las db en la versión que ya tenemos, alguna db da error y la columna 15 RESISTANCE no existe en la versión 0.8.13.
También quiero añadir la posibilidad de no ejecutar este paso: _run_abricate = False # If you want to omit this step, set it to False (Default: False)_. Se puede llamar como sea.
El término `bacteria_database` no es muy adecuado, sería mejor `antimicrobial_resistance_database` si puedes cambiarlo. Así, el comando de ABRicate quedaría:

`/path/to/abricate /path/to/Mauve_reordered_contigs/*.fasta --db $database --mincov $número --minid $número > /Antimicrobial_resistance_genes/AMR_genes_ABRicate_database.format`

donde:
`--mincov (número)` (90 por defecto). Opcional, se debe incluir en el archivo wombat_config.py con la descripción `# Minimum DNA % coverage for considering an antimicrobial resistance gene as present. Default: 90.`
`--minid (número)` (90 por defecto). Opcional, se debe incluir en el archivo wombat_config.py con la descripción `# Minimum DNA % identity for considering an antimicrobial resistance gene as present. Default: 90.`
`AMR_genes_ABRicate_database.format` es el output con el formato que quieras, que se localizará en la carpeta Antimicrobial_resistance_genes. Si es posible, la palabra _database_ del nombre de ese output debería ser la database seleccionada en la opción `-db`. Si esta es card, el nombre del archivo será AMR_ABRicate_card.format 

Sobre el archivo AMR_genes_ABRicate_database.format, debes hacer la misma modificación para la **primera columna** que has hecho con el output MLST_edited. Es decir, del path que se indica en la primera columna referido a cada Sample, dejar solo lo correspondiente al nombre de Sample.

Lo que viene a continuación lo valoras, la finalidad es la misma que con el post-procesamiento de tBLASTn, crear una matriz 1/0 de presencia/ausencia con el archivo AMR_genes_ABRicate_card.format. Si el código que tienes es más fácil de implementar que esta otra posibilidad, lo puedes incorporar como prefieras. Sería utilizar la columna 1 con las Samples y la 6 GENE con los genes (en la nueva versión de ABRicate), teniendo en cuenta los valores de la columnas 10 %COVERAGE y 11 %IDENTITY (en la nueva versión de ABRicate). Se considera presencia cuando % coverage y % identity son superiores a `--mincov $número` y `--minid $número`, respectivamente. Estaría bien incluir la información de la columna 15 RESISTANCE. Así, tendría el mismo formato que la tabla de tBLASTn (filas: genes, columnas: cepas). 
******************************
ABRicate ha incorporado esa posibilidad y genera un summary report con una matriz similar a una de presencia/ausencia (la versión última de conda lo tiene incorporado) con el output anterior (creo que debes actualizar la versión de conda en este caso):

`/path/to/abricate /path/to/Mauve_reordered_contigs/*.fasta --summary /Antimicrobial_resistance_genes/AMR_genes_ABRicate_database.format > /Antimicrobial_resistance_genes/AMR_genes_ABRicate_database_matrix.format`

Se debe obtener un archivo como este: [card_abricate_summary.txt](https://github.com/JoseBarbero/Wombat/files/4634022/card_abricate_summary.txt). En esa matriz, los puntos **.**, deben sustituirse por 0 y todos los números (donde no haya "punto") por 1. Aquí se habla de ello https://github.com/tseemann/abricate/issues/73#issue-386840959, supongo que no lo habrá actualizado para cuando lo hagas. También sucede esto https://github.com/tseemann/abricate/issues/141#issue-618908425. Como creo que sucederá igual que con el otro issue, si puedes, introduce las Samples que falten comparando con el input_files.csv y rellena los campos siguientes con _0_.
******************************

### OPCIÓN 2. Nueva herramienta AMRFinderPlus https://github.com/ncbi/amr

En AMRFinder, la opción amrfinder -u es interesante para actualizar las bases de datos una vez se incorpora la herramienta a Wombat. No sé esto como hay que gestionarlo, igual cuando se actualice Wombat, ¿se actualizarían esas db?

Se puede desactivar la ejecución de esta herramienta incorporando una opción en wombat_config.py. Se puede poner igual que para ABRicate: _run_amrfinder = True # If you want to omit this step, set it to False (Default: True)_. Se puede llamar como sea.

Para ejecutar AMRFinder sin error, es necesario modificar el archivo .gff generado por el anotador PROKKA o DFAST. Para cada anotación, en la columna 9 de ese archivo, debe aparecer un nuevo campo llamado Name=xxxxx donde xxxxxx es el contenido que aparece en el archivo .faa del anotador entre '>' y el primer espacio:
- Para PROKKA, el contenido de 'Name=' es el mismo que el contenido de 'ID='. Creo que si modificas “ID=” por “Name=” es suficiente, aunque yo utilicé un comando que duplicaba el campo ID y luego cambiaba un ID por Name. 
- Para DFAST, el contenido de 'Name=' es la unión de 'ID=' y 'locus_tag=', con el símbolo '|' entre medias, para que tenga la siguiente forma MGA_1|Sample_L_0001.

Cada nuevo archivo .gff modificado para cada cepa no debe aparecer en ningún sitio cuando se ejecute Wombat. Aquí tienes un ejemplo de cómo debe ser ese archivo .gff (con PROKKA) 
[Sample_for_amrfinder.txt](https://github.com/JoseBarbero/Wombat/files/4579722/Sample_for_amrfinder.txt)

El comando que vamos a usar para AMRFinder es:
`amrfinder -n /path/to/each/annotation_directory/Sample/Sample.fna -p /path/to/each/annotation_directory/Sample/Sample.faa -g /path/to/each/annotation_directory/Sample/Sample.gff(el modificado antes) --organism Genus_Sample --plus -i $número -c $número -o /Antimicrobial_resistance_genes/AMR_genes_AMRFinder_Sample.format`

donde:

`--organism Genus_Sample` es la columna 4 referida a Genus del archivo input_files.csv. Si esa columna no se rellena, no se incluirá esta opción. Añade un comentario porque más adelante cuando se incorpore Kraken, se hará referencia al output de Kraken (lo mismo en el comando de PROKKA o DFAST que hacen referencia a --genus y --species o --organism, respectivamente).

`-o /Antimicrobial_resistance_genes/Sample.format` es el directorio del output. Para cada Sample, se generará un archivo en el formato que mejor consideres. Después de ejecutar AMRFinder para cada Sample, se deben unir todos los outputs en un archivo llamado AMR_genes_AMRFinder con el formato que quieras (dentro del directorio con el nombre Antimicrobial_resistance_genes). Únicamente debe permanecer este último archivo. Cada archivo de cada Sample se debe eliminar.

Los siguientes parámetros serán opcionales en el archivo wombat_config.py:
`-i (número)` #Minimum proportion identical translated AA residues for considering an antimicrobial resistance gene (0-1). Default: 0.9
`-c (número)` #Minimum coverage of reference protein sequence for for considering an antimicrobial resistance gene (0-1). Default: 0.9

A partir del archivo AMR_genes_AMRFinder se va a generar una tabla llamada AMR_genes_AMRFinder_resume con el siguiente aspecto [AMR_genes_resume.txt](https://github.com/JoseBarbero/Wombat/files/4580327/AMR_genes_resume.txt) en la carpeta Antimicrobial_resistance_genes. Para ello, se deben utilizar solo los resultados obtenidos cuando en las columnas 10 “Element Type” y 11 “Element subtype” aparezca “AMR”. En esta nueva tabla, la primera columna se llamará Sample y será la columna 1 del archivo anterior y el encabezado de las siguientes columnas se obtendrá a partir del contenido de la columna 12 “Class”. Se añadirán tantas columnas como contenidos diferentes se puedan encontrar en esa columna 12. Por ejemplo, si en esa columna hay dos posibilidades, BETA-LACTAM y TETRACYCLINE, la tabla tendrá 3 columnas con los encabezados: Sample, BETA-LACTAM y TETRACYCLINE (o todo es mayúscula o todo en minúscula, a mí me gusta más en minúscula y primera letra mayúscula, aunque como sea posible). Para cada Sample, el contenido de las columnas BETA-LACTAM y TETRACYCLINE (y sucesivas) se obtendrá de la columna 7 “Gene symbol”, cuando la columna 12 sea BETA-LACTAM o TETRACYCLINE, respectivamente. Por último, aquellas celdas vacías deben rellenarse con un guion '-' y se indicará en la última fila de la tabla _'-' means no AMR gen found._
(si quieres trasponer filas por columnas, para que tenga el mismo formato que las tablas anteriores, puedes)

**Comment by ireneortega** [comment]
En este hilo, el propio autor reconoce que AMRFinderPlus es mejor que ABRicate: https://github.com/tseemann/abricate/issues/130#issue-587332039

**Comment by JoseBarbero** [comment]
Me está dando problemas la parte de AMRFinder. Al gff que sale de prokka le tengo que meter un campo Name=****. Pero algunas filas ya tienen un campo Name. ¿Qué debería hacer con esos nombres? ¿Los sobrescribo con el id?

**Comment by ireneortega** [comment]
Perdón, no era consciente de ello y no te había indicado toda la información necesaria. En resumen, debe aparecer una etiqueta Name cuyo contenido sea el mismo que la etiqueta ID del archivo bruto .gff de PROKKA. Pienso que lo más fácil es:
1. Renombrar las etiquetas Name= por OldName=
2. Modificar ID= por Name=

Con eso debería funcionar sin problemas. Si aun así te da problemas, los autores de AMRFinder me dijeron que hiciera la siguiente modificación:
1. Renombrar las etiquetas Name= por OldName=
2. Duplicar el campo ID= al mismo tiempo que se cambia ID=por Name=
En este segundo caso, el archivo final tendría la siguiente forma: [Sample_for_amrfinder.txt](https://github.com/JoseBarbero/Wombat/files/4680866/Sample_for_amrfinder.txt)

**Comment by JoseBarbero** [comment]
Genial. Gracias.

**Comment by JoseBarbero** [comment]
Estoy viendo que Roary da problemas con la estructura que me comentas para DFast _("el contenido de 'Name=' es la unión de 'ID=' y 'locus_tag=', con el símbolo '|' entre medias, para que tenga la siguiente forma MGA_1|Sample_L_0001 ")_ .
¿Por qué tiene que tener esa estructura y no solamente el ID como en Prokka?
Lo digo porque con Prokka, poniendo el ID en Name, Roary funciona bien.

**Comment by ireneortega** [comment]
Por esto: _Para cada anotación, en la columna 9 de ese archivo, debe aparecer un nuevo campo llamado Name=xxxxx donde xxxxxx es el contenido que aparece en el archivo .faa del anotador entre '>' y el primer espacio_ Es decir, para la correcta ejecución de AMRFinder.

Pero, esta modificación no debe afectar a los archivos input .gff de Roary (si se posible), es solo una modificación de los inputs para AMRFinder.
En Roary, los inputs son directamente los archivos .gff de PROKKA y DFAST (lo que ya estaba)

**Comment by JoseBarbero** [comment]
Hola, Irene.

Estoy dándole vueltas a esto y quedaría el fichero AMR_genes_resume.txt que te adjunto.
El caso es que en la primera columna no tenemos una sample sino un protein identifier. Esto hace que a la hora de meter esa información en el report final no tengamos una fila para cada sample, sino varias.
¿Cómo podríamos incluir esa información en el report final? ¿Unifico todas las filas de una sample en la misma?
![image](https://user-images.githubusercontent.com/17479313/83245371-ececc280-a1a0-11ea-9366-3a735c676464.png)

**Comment by ireneortega** [comment]
Creo que, en el archivo AMR_genes_AMRFinder, falta añadir una primera columna con el nombre de Sample. Este nombre se puede sacar a la partir de la siguiente columna (protein identifier). En cada anotador, ese identificador tiene esta forma:
– PROKKA: **Sample**_L_xxxxx.
– DFAST: MGA_xxx|**Sample**_L_xxxxx.

Con esa modificación, la primera columna de esa tabla resumen sería la columna Sample anterior (y no protein identifier). Después, como bien dices, todos los resultados de una misma Sample deben aparecer en la misma fila.

Si te da error, pásame el archivo AMR_genes_AMRFinder obtenido con PROKKA y DFAST y lo miro más detalladamente.

**Comment by ireneortega** [comment]
Con la última actualización, ha surgido este error: [wombat_log.txt](https://github.com/JoseBarbero/Wombat/files/4741714/wombat_log.txt)

**Comment by ireneortega** [comment]
En la carpeta del anotador, no debe mostrarse la carpeta _AMR_format_files_ y tampoco debe aparecer en ningún sitio tras la ejecución de Wombat.

**Comment by ireneortega** [comment]
Para verificar, las opciones: `mincov `y `minid` deben incluir el =, es decir, si algún resultado tiene % identidad o cobertura = 90 cuando mincov y minid: 90 , se debe indicar como 1 en la matriz (no sé si está considerado el "igual" o no)

**Comment by ireneortega** [comment]
Vamos a cambiar los nombres de los archivos:
De la ejecución de ABRicate: AMR_ABRicate_card > **AMR_genes_ABRicate_card**
De la ejecución de AMRFinder: AMR_genes_resume > **AMR_genes_AMRFinder_matrix** (¿te convence el nombre de matrix cuando el contenido no es 1/0? Si no puedes cambiar la palabra por otra, o si consideras que _resume_ es la mejor, se queda como está)

**Comment by JoseBarbero** [comment]
En teoría el filtrado para que Element type y subtype sean AMR ya está hecho. ¿Puedes pasarme tu fichero AMR_genes_AMRFinder.tsv y AMR_genes_resume para ver qué puede estar pasando?

PD: Para un futuro creo que sería mejor crear nuevos issues para todas estas cosas mejor que reabrir issues antiguos (siempre que sean problemas diferentes) para dejar todo bien diferenciado en el repositorio. Se pueden mencionar issues cerrados si se quiere remarcar la relación.

**Comment by ireneortega** [comment]
En este archivo [AMR_genes_resume.txt](https://github.com/JoseBarbero/Wombat/files/4803296/AMR_genes_resume.txt), aparecen en columnas todos los campos diferentes de la columna CLASS del archivo [AMR_genes_AMRFinder.txt](https://github.com/JoseBarbero/Wombat/files/4803295/AMR_genes_AMRFinder.txt). No sé si igual se ponen las columnas antes del filtrado... y luego la información se completa cuando se hace el filtrado.

El archivo _resume_ debería quedar como [AMR_genes_resume(2).txt](https://github.com/JoseBarbero/Wombat/files/4803322/AMR_genes_resume.2.txt)


PD: Perdón, cualquier otra cosa que se pueda hacer mejor, me lo dices.
