### ISSUE TITLE
Virulence genes and Roary directory

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#92]
Se debe crear una carpeta llamada Virulence_genes donde se situará la carpeta BLAST_custom_virulence_genes.

Los archivos de la carpeta Roary_pangenome/Roary deben aparecer directamente en Roary_pangenome, así quitamos esa carpeta "innecesaria".

**Comment by ireneortega** [comment]
El nombre del directorio de los outputs de Roary coincide con la carpeta que se crea al inicio, Roary_pangenome. Esto implica que, cuando se ejecuta Roary, como ya existe un directorio de salida con el mismo nombre, Roary crea otra con el nombre Roary_pangenome_xxxxxx. Esto afecta a la ruta de los inputs para roary_plots ya que no los encuentra donde deberían estar, esto es en Roary_pangenome, y no donde realmente se encuentran Roary_pangenome_xxxxxx:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/irene/Documentos/Wombat_OUTPUT_20200516_115738/Roary_pangenome/accessory_binary_genes.fa.newick'`

Creo que moviendo los archivos de Roary_pangenome_xxxxxx a Roary_pangenome y eliminando la carpeta Roary_pangenome_xxxxxx se solucionaría el problema. Pero lo ideal es que los outputs se localizaran en la carpeta que se crea al inicio y esto no sé si es posible.

**Comment by JoseBarbero** [comment]
Estoy intentando replicar este error y a mí no me pasa. ¿Estás en la última versión?

**Comment by ireneortega** [comment]
Sí, actualicé antes de ejecutar. Además, se genera el archivo VF_matrix entre los últimos cambios. A la tarde, lo vuelvo a ejecutar y te digo.

**Comment by JoseBarbero** [comment]
No veo qué puede estar pasando. Si puedes, pásame el .log a ver si veo algo que me dé pistas.

**Comment by ireneortega** [comment]
[wombat_log.txt](https://github.com/JoseBarbero/Wombat/files/4643295/wombat_log.txt)

Osea los archivos de Roary no están donde deberían. Se crean las carpetas Roary_pangenome/Roary_plots (ambas vacías) y Roary_pangenome_1589628735 (tiene el output de Roary que debería estar en Roary_pangenome para que funcione roary_plots)

**Comment by JoseBarbero** [comment]
He hecho un pequeño cambio que puede que lo solucione, pero lo estoy haciendo a ciegas porque no consigo replicar ese error en mi PC. Si lo vuelves a ejecutar, actualiza primero y me cuentas.

**Comment by ireneortega** [comment]
Ahora sale otro error completamente diferente: [wombat_log.txt](https://github.com/JoseBarbero/Wombat/files/4649595/wombat_log.txt)

**Comment by ireneortega** [comment]
Solucionado. Gracias!
