### ISSUE TITLE
Edit VirulenceGenes.tab

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#93]
El archivo VirulenceGenes.tab de la carpeta ABRicate_virulence_genes pasará a llamarse ABRicate_virulence_genes.tab y se situará en Virulence_genes, así quitamos la carpeta ABRicate_virulence_genes.

Además, deberá editarse la primera columna. Pasará de llamarse #FILE a SAMPLE y el contenido de esta columna será únicamente el nombre de Sample, no la ruta.

**Comment by JoseBarbero** [comment]
No me queda muy clara la primera parte de este issue. Ahora mismo no hay una carpeta "Virulence_genes". ¿Lo que quieres es que la carpeta que ahora se llama "ABRicate_virulence_genes" pase a llamarse "Virulence_genes"?

**Comment by ireneortega** [comment]
Este issue está relacionado con este https://github.com/JoseBarbero/Wombat/issues/92#issue-612543270 
Vamos a unificar los resultados de genes de virulencia en una sola carpeta, tanto los resultados de ABRicate como de BLAST. La carpeta se llamará Virulence_genes y tendrá el nuevo archivo renombrado ABRicate_virulence_genes.tab con la carpeta BLAST_custom_virulence_genes.

**Comment by JoseBarbero** [comment]
De acuerdo, no me había puesto con el otro todavía.
Gracias.

**Comment by ireneortega** [comment]
El archivo Virulence_genes/VirulenceGenes.tab debe llamarse Virulence_genes_ABRicate_VFDB.tab

**Comment by ireneortega** [comment]
De la misma forma en que se hace el archivo _AMR_genes_ABRicate_database_matrix_ a partir del archivo _AMR_ABRicate_database_ https://github.com/JoseBarbero/Wombat/issues/89#issue-612447734, se debe crear la misma tabla con el mismo formato pero utilizando como input el archivo _Virulence_genes_ABRicate_VFDB_, para crear una matriz llamada _Virulence_genes_ABRicate_VFDB_matrix_ en la misma localización.

**Comment by ireneortega** [comment]
En el archivo Virulence_genes_ABRicate_VFDB_matrix, el encabezado de la primera columna debe llamarse GENE, para que coincida con el nombre de la columna de la cual se extrae esa información del archivo Virulence_genes_ABRicate_VFDB. La columna 5 debe contener la información de la columna 14 PRODUCT del archivo anterior y llamarse de la misma forma, es decir, PRODUCT.

**Comment by JoseBarbero** [comment]
Dos dudas:

¿Estos cambios quieres que se apliquen también al fichero AMR_genes_ABRicate_card_matrix.tsv?

Las columnas del fichero Virulence_genes_ABRicate_VFDB_matrix varían en función de las cepas. ¿Con columna 5 te refieres a que lo añada al final de lo que hay ahora, o a que sustituya la actual columna TYPE con el contenido de PRODUCT?

**Comment by ireneortega** [comment]
Creo recordar que en AMR_genes_ABRicate_card_matrix salía bien, pero el procesamiento de ambos outputs es el mismo por ejecutarse con la misma herramienta. 

Sí, la columna 5 es la última, que no te lo indiqué bien. Esa debe ser PRODUCT (en AMRFinder es Type porque así sale en el output, pero en ABRicate sale como PRODUCT)

**Comment by ireneortega** [comment]
Perdón, para el archivo AMR_genes_ABRicate_card_matrix, la última columna debe extraerse de la columna 15 RESISTANCE. Pero, en el archivo Virulence_genes_ABRicate_vfdb_matrix, esa columna 15 RESISTANCE sale vacía, entonces cambia esa columna por la 14 PRODUCT.
