### ISSUE TITLE
tBLASTn postprocessing

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#95]
Sobre el archivo BLASToutput_VF_custom_edited.txt se deben hacer estas modificaciones:
- El nombre de la columna 1 pasará de llamarse 'query id' a llamarse 'Protein'.
- El nombre de la columna 3 pasará de llamarse 'query length' a llamarse 'Protein length'.
- El nombre de la columna 4 pasará de llamarse 'protein cover %' a llamarse '% protein cover'.
- El nombre de la columna 5 pasará de llamarse '% identity' a llamarse '% protein identity'.
- En el nombre de las columnas 9 y 10, 'query...' se sustituirá por 'Protein...' de forma que se llamarán Protein start/end. En las dos siguientes columnas, 11 y 12, de igual forma, 'subject' se sustituirá por 'Sample'.
- Para el resto de columnas, la primera letra será con mayúscula.
- La columna 2 'subject id' se separará en dos llamadas 'Sample' (nueva columna 2) y 'Contig sample' (nueva columna 3). El contenido de la nueva columna 'Sample' será lo que ahora aparece en la columna 2 hasta la primera barra baja _. El contenido de la nueva columna 'Contig sample' será lo que aparece a continuación de la primera barra baja, _, hasta el final. Ejemplo: H1_C_11_length_81846, debe separarse en H1 (en 'Sample') y C_11_length_81846 (en 'Contig sample').
- Incluir nueva columna 2 llamada 'Protein type'. Para cada Protein, el contenido de esta columna será la palabra en posición 2 de cada entrada '>' del archivo VF_custom.txt (Stress, Capsule, Invasion, etc.). Una vez hecho esto, lo ideal es que los resultados se ordenaran por orden alfabético de esta columna 'Protein type' y, después, por orden alfabético de la columna 'Protein' y, luego, de la columna 'Sample'. Si esto no es posible, deja los resultados como salgan o si no, modifico el archivo VF_custom para que estén ordenadas las secuencias.

Con ese archivo, vamos a hacer una matriz de 1/0 = presencia/ausencia llamada VF_matrix que si situará en la carpeta Virulence_genes/BLAST_custom_virulence_genes. Tendrá esta forma: [VF_matrix.txt](https://github.com/JoseBarbero/Wombat/files/4598115/VF_matrix.txt). La primera columna se llamara 'Sample' y serán las diferentes Samples que aparecen en el archivo input_files.csv (ordenadas alfabéticamente). No son todas las posibles Samples que aparecen en la tercera columna del output de BLAST porque puede que no aparezcan todas si alguna no contiene ninguna proteína. Entonces esa matriz estaría incompleta. El nombre de la columna 2 y sucesivas de esta matriz, serán todas las proteínas que aparezcan en el archivo VF_custom.txt, para cada entrada, entre el símbolo '>' y el primer espacio. No se puede utilizar la columna 1 para ello por el mismo motivo anterior. Encima de cada proteína se indicará la categoría a la que pertenece, utilizando la columna 'Protein type'. Si se puede, las columnas 2 y siguientes se ordenarán por orden alfabético de cada categoría 'Protein type' y, en cada categoría, por orden alfabético de los genes.

Para indicar **presencia = 1**, una proteína (columna 1) debe estar en una Sample (nueva columna 3) si la nueva columna 6 _% protein cover_ es superior a un número **y** la nueva columna 7 _% protein identity_ es superior a un número. En el archivo wombat_confip.py, se indicarán estos números:
% protein cover > 90 #Minimum % protein cover for considering a virulence gene as present. Default: 90.
% protein identity > 90 #Minimum % protein identity for considering a virulence gene as present. Default: 90.

Si no se cumple alguna condición de protein cover o protein identity, se pondrá 0.

En la última fila de esa matriz, debajo de ella, se indicará lo siguiente: _Coverage > (número) % and identity > (número) %) on each sample for considering a virulence gene as present._

El caso de capA es especial porque aunque es una bacteria, la proteína tiene 2 ORFs, separados por un nucleótido (este no forma parte de la proteína). Entonces, nunca se va a identificar como presente si se utiliza la secuencia completa de la proteína (los 2 ORFs unidos) y tBLASTn. En el nuevo archivo VF_custom.txt anterior, he cambiado la secuencia de esta proteína por los 2 ORFS: capA_ORF1 y capA_ORF2. Entonces, en el output de BLAST habrá dos "proteínas" en la primera columna cuyos resultados se deben considerar de forma conjunta para considerar presencia/ausencia de capA. Así, capA estará presente si tanto % protein cover > 90 y % protein identity > 90 para capA_ORF1 y capA_ORF2 a la vez, es decir, 4 condiciones.

**Comment by JoseBarbero** [comment]
Estoy creando la tabla VF_matrix y no veo muy bien la distribución. Meter dos filas de cabecera hace que no sigamos el formato csv con una fila de cabecera. Solo tendría sentido en excel.
¿No sería mejor poner las proteínas como filas y tener como columnas los nombres de las cepas y una columna extra con el tipo de cada proteína? Así se sigue el formato estándar y tiene la misma información.

Te adjunto un ejemplo:
[VF_matrix.txt](https://github.com/JoseBarbero/Wombat/files/4622793/VF_matrix.txt)

**Comment by ireneortega** [comment]
Vale, si te resulta más fácil así, no hay problema. Luego en Excel se puede editar rápidamente en tal caso.
El formato que tenía yo en mente era suponiendo que se quisiera publicar la tabla y que en una página no entrara, de forma que se pudiera leer en dos o más partes sin perder información para ello. Ahora no recuerdo si en alguna otra tabla la diseñé de forma similar, pero las puedes modificar como más fácil sea, siempre y cuando se pierda la menor información posible.

**Comment by JoseBarbero** [comment]
De acuerdo.

**Comment by ireneortega** [comment]
Se me olvidó comentarte que hay que tener en cuenta la región de la Sample en la que se hace el alineamiento (columnas Sample start y Sample end). En los casos en que las secuencias de las proteínas de la db son similares, se produce el alineamiento en una región casi igual, y se podría dar el caso de que el resultado fuera de presencia de ambas secuencias en la misma región aproximada, cuando solo puede tener una, la que mejor % identity y % coverage tenga. Esto no sé si se puede configurar automáticamente porque la región de la Sample que alinea (columnas de antes) es altamente probable que no sea igual para diferentes proteínas de la db, es decir, que esa región esté "movida" x nucleótidos, pero compartan un alto % de nucleótidos que alinean en ambos casos. Si necesitas casos donde suceda esto, te lo puedo indicar

**Comment by JoseBarbero** [comment]
En la reunión si quieres hablamos de esto, porque no me queda muy claro.

**Comment by ireneortega** [comment]
Todavía no se ha resuelto el problema de la matriz. Siguen saliendo 0 en resultados en los que % identidad y % cobertura > 90 %. He obtenido el mismo resultado que la otra vez.

**Comment by JoseBarbero** [comment]
No veo qué puede estar pasando. Voy a necesitar un ejemplo. La otra vez me pasaste un excel con ejemplos, si me pasas los genomas correspondientes lo miro para esos casos.

**Comment by ireneortega** [comment]
Otra opción que se me ocurre poner, en la línea 531 del código # Remove low identity rows, las condiciones opuestas a minid y mincov, entonces se eliminarán los alineamientos que están interfiriendo en los resultados de la matriz (o cambiar la condición y que se mantengan solo los resultados de ambas condiciones). Después, solo sería poner 1/0 según coincida Protein con Sample en el archivo BLASToutput_VF_custom_edited. Esto eliminaría la opción evalue del archivo de configuración, porque ya no sería necesaria.

Considerando lo anterior, otra opción sería crear un archivo temporal a partir de BLASToutput_VF_custom_edited, que tenga solo los alineamientos en los que se cumplen ambas condiciones, y que sea el utilizado para hacer la matriz.

La configuración actual es para que el usuario tenga la posibilidad de trabajar con los resultados de BLAST en bruto, sin haberlos prefiltrado, y que esto se haga únicamente para la matriz. Si crees que la configuración que hayas hecho es la mejor, mañana te paso todo lo necesario para que lo compruebes.

**Comment by JoseBarbero** [comment]
Preferiría probar con los que te fallan a ti, porque lo que falla tiene que ser algo muy simple que se me está escapando.

**Comment by ireneortega** [comment]
Para verificar, cuando se genera la matriz, las opciones: `protein_cover` y `protein_identity` deben incluir el =, es decir, si algún resultado tiene % identidad o cobertura = 90 cuando se configuren como 90 , se debe indicar como 1 en la matriz (no sé si está considerado el "igual" o no).

Es decir, deben considerar resultados **=>**

**Comment by ireneortega** [comment]
Vamos a cambiar los nombres de los archivos:
BLASToutput_VF_custom > BLAST_custom_VFDB
BLASToutput_VF_custom_edited > BLAST_custom_VFDB_edited (no me convence la palabra _edited_, tiene que ser algo que describa que se han filtrado resultados y contiene más información que el archivo anterior. No sé si se te ocurre algo).
VF_matrix > BLAST_custom_VFDB_matrix
VF_custom > custom_VFDB (supongo que se cambiará solo con esto https://github.com/JoseBarbero/Wombat/issues/94#issuecomment-643661974)
